# Generated by scripts/update-packaging-manifests.nu on each release.
# Install: brew tap royalflamejlh/spnd https://github.com/Royalflamejlh/spnd && brew install spnd
class Spnd < Formula
  desc "Interactive terminal UI for coding-agent token usage and spend"
  homepage "https://github.com/Royalflamejlh/spnd"
  version "0.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Royalflamejlh/spnd/releases/download/v0.0.0/spnd-darwin-arm64.tar.gz"
      sha256 "52f94f821c2411251c0a432496dde8ca0f5bc90d6138feb8ef455558b46d42f0"
    else
      url "https://github.com/Royalflamejlh/spnd/releases/download/v0.0.0/spnd-darwin-x64.tar.gz"
      sha256 "52f94f821c2411251c0a432496dde8ca0f5bc90d6138feb8ef455558b46d42f0"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/Royalflamejlh/spnd/releases/download/v0.0.0/spnd-linux-arm64.tar.gz"
      sha256 "52f94f821c2411251c0a432496dde8ca0f5bc90d6138feb8ef455558b46d42f0"
    else
      url "https://github.com/Royalflamejlh/spnd/releases/download/v0.0.0/spnd-linux-x64.tar.gz"
      sha256 "52f94f821c2411251c0a432496dde8ca0f5bc90d6138feb8ef455558b46d42f0"
    end
  end

  def install
    bin.install "spnd"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/spnd --version")
  end
end
