#!/usr/bin/env nix
#! nix shell --inputs-from .. nixpkgs#nushell --command nu

# Regenerates the Homebrew formula and Scoop manifest for a release from
# dist/SHA256SUMS, so both always describe the assets that were actually
# uploaded.
def main [--version: string] {
    if ($version | is-empty) {
        error make {msg: 'pass --version <semver without the v prefix>'}
    }
    let repo_root = (
        $env.CURRENT_FILE
        | path dirname
        | path join ..
        | path expand
    )
    let sums = (
        open ($repo_root | path join dist SHA256SUMS)
        | lines
        | where {|line| ($line | str trim) != '' }
        | parse '{hash}  {file}'
    )
    let sha = {|asset|
        let matches = $sums | where file == $asset
        if ($matches | is-empty) {
            error make {msg: $'dist/SHA256SUMS has no entry for ($asset)'}
        }
        $matches | get 0.hash
    }
    let base = $'https://github.com/Royalflamejlh/spnd/releases/download/v($version)'

    let formula = (
        formula-template
        | str replace --all '@VERSION@' $version
        | str replace --all '@BASE@' $base
        | str replace --all '@SHA_DARWIN_ARM64@' (do $sha 'spnd-darwin-arm64.tar.gz')
        | str replace --all '@SHA_DARWIN_X64@' (do $sha 'spnd-darwin-x64.tar.gz')
        | str replace --all '@SHA_LINUX_ARM64@' (do $sha 'spnd-linux-arm64.tar.gz')
        | str replace --all '@SHA_LINUX_X64@' (do $sha 'spnd-linux-x64.tar.gz')
    )
    $formula | save --force ($repo_root | path join Formula spnd.rb)

    let scoop = {
        version: $version
        description: 'Interactive terminal UI for coding-agent token usage and spend'
        homepage: 'https://github.com/Royalflamejlh/spnd'
        license: 'MIT'
        architecture: {
            '64bit': {
                url: $'($base)/spnd-win32-x64.zip'
                hash: (do $sha 'spnd-win32-x64.zip')
            }
            arm64: {
                url: $'($base)/spnd-win32-arm64.zip'
                hash: (do $sha 'spnd-win32-arm64.zip')
            }
        }
        bin: 'spnd.exe'
    }
    $scoop | to json --indent 2 | $in + "\n" | save --force ($repo_root | path join bucket spnd.json)
}

def formula-template []: nothing -> string {
    r##'# Generated by scripts/update-packaging-manifests.nu on each release.
# Install: brew tap royalflamejlh/spnd https://github.com/Royalflamejlh/spnd && brew install spnd
class Spnd < Formula
  desc "Interactive terminal UI for coding-agent token usage and spend"
  homepage "https://github.com/Royalflamejlh/spnd"
  version "@VERSION@"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "@BASE@/spnd-darwin-arm64.tar.gz"
      sha256 "@SHA_DARWIN_ARM64@"
    else
      url "@BASE@/spnd-darwin-x64.tar.gz"
      sha256 "@SHA_DARWIN_X64@"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "@BASE@/spnd-linux-arm64.tar.gz"
      sha256 "@SHA_LINUX_ARM64@"
    else
      url "@BASE@/spnd-linux-x64.tar.gz"
      sha256 "@SHA_LINUX_X64@"
    end
  end

  def install
    bin.install "spnd"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/spnd --version")
  end
end
'##
}
